OnlineBookingSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, about_view, contact_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('counsellor/', include('counsellor.urls')),
    path('client/', include('client.urls')),
    path('admin/', include('systemAdmin.urls')),
    path('availability/', include('availability.urls')),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

availability/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
    UpdateAvailabilityView,
    DeleteAvailabilityView,
)


app_name='availability'
urlpatterns=[
    path('<int:pk>/update-availability/', UpdateAvailabilityView.as_view(), name='update-availability'),
    path('<int:pk>/delete-availability/', DeleteAvailabilityView.as_view(), name='delete-availability'),
    ]

client/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	client_login_view,
    client_form_view,
    all_client_list_view,
    edit_client_view,
    update_client_view,
    delete_client_view,
    create_appointment_view,
    my_appointments_view,
    my_notifications_view,
    my_counsellors_view,
    DeleteAppointmentView,
    my_profile_view,
    reschedule_appointment_view,
)

app_name="client"

urlpatterns=[
	path('login/', client_login_view, name='client-login'),
    path('form/', client_form_view, name='client-form'),
    path('list/',all_client_list_view, name='all-client-list'),
    path('edit/<int:id>',edit_client_view, name='edit-client'),
    path('update/<int:id>',update_client_view, name='update-client'),
    path('delete/<int:id>',delete_client_view, name='delete-client'),
    path('create-appointment/', create_appointment_view, name='create-appointment'),
    path('my-appointment/', my_appointments_view, name='my-appointment'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('my-profile/', my_profile_view, name='my-profile'),
    path('my-counsellors/', my_counsellors_view, name='my-counsellors'),
    path('<int:pk>/reschedule-appointment/', reschedule_appointment_view, name='reschedule-appointment'),
    path('<int:pk>/delete-appointment/', DeleteAppointmentView.as_view(), name='delete-appointment'),
]

counsellor/urls.py
from django.urls import path

from .views import(
	counsellor_details_view,
	counsellor_details_with_availability_view,
	counsellor_form_view,
	counsellor_login_view,
    all_counsellor_list_view,
    edit_counsellor_view,
    update_counsellor_view,
    delete_counsellor_view,
    my_availability_view,
    give_availability_view,
    show_availability_view,
    my_clients_view,
    my_appointments_view,
    my_notifications_view,
    my_profile_view,
    DeleteAppointmentView,
)

app_name="counsellor"

urlpatterns=[
	path('', counsellor_details_view, name='counsellor-details'),
	path('counsellor-details/', counsellor_details_with_availability_view, name='counsellor-details-with-availability'),
    path('form/', counsellor_form_view, name='counsellor-form'),
    path('login/', counsellor_login_view, name='counsellor-login'),
    path('list/',all_counsellor_list_view, name='all-counsellor-list'),
    path('edit/<int:id>',edit_counsellor_view, name='edit-counsellor'),
    path('update/<int:id>',update_counsellor_view, name='update-counsellor'),
    path('delete/<int:id>',delete_counsellor_view, name='delete-counsellor'),
    path('give-availability/',give_availability_view, name='give-availability'),
    path('my-availabiltiy/',my_availability_view, name='my-availability'),
    path('show-availability/<int:id>',show_availability_view, name='show-availabiltiy'),
    path('my-clients/',my_clients_view, name='my-clients'),
    path('my-appointments/',my_appointments_view, name='my-appointments'),
    path('my-notifications/',my_notifications_view, name='my-notifications'),
    path('my-profile/',my_profile_view, name='my-profile'),
    path('<int:pk>/delete-appointments/',DeleteAppointmentView.as_view(), name='delete-appointments'),
]

manage/manage/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

systemAdmin/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	admin_login_view,
    admin_change_password_view,
    admin_update_password_view,
    CreateWorkHoursView,
    UpdateWorkHoursView,
    WorkHoursListView,
    WorkHoursUpdateView,
    WorkHoursDeleteView,
    my_notifications_view,
    all_appointments_view,
    DeleteAppointmentsView,
    CreateCounsellorView,
    CreateClientView,
)


app_name='systemAdmin'
urlpatterns=[
	path('logIn/',admin_login_view,name='admin-logIn'),
    path('change-password/', admin_change_password_view, name='admin-change-password'),
    path('update-password/', admin_update_password_view, name='admin-update-password'),
    path('create-workhours/', CreateWorkHoursView.as_view(), name='create-workhours'),
    path('<int:pk>/update-workhours/', UpdateWorkHoursView.as_view(), name='update-workhours'),
    path('list-workhours/', WorkHoursListView.as_view(), name='list-workhours'),
    path('<int:pk>/update-workhours/', WorkHoursUpdateView.as_view(), name='update-workhours'),
    path('<int:pk>/delete-workhours/', WorkHoursDeleteView.as_view(), name='delete-workhours'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('all-appointments/', all_appointments_view, name='all-appointments'),
    path('create-counsellor/', CreateCounsellorView.as_view(), name='create-counsellor'),
    path('create-client/', CreateClientView.as_view(), name='create-client'),
    path('<int:pk>/delete-appointments/', DeleteAppointmentsView.as_view(), name='delete-appointments'),
   
]

counsellor/models.py
from django.db import models
from django import forms
from django.urls import reverse
import datetime
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class Counsellor(models.Model):
	# max_length is a required field for char field
	#name of ht counsellor
	name 		= models.CharField(max_length=100)

	#username of ht counsellor
	username 		= models.CharField(max_length=10)

	#login password of hte user
	password	= models.CharField(max_length=32,default="mydjango123")

	#address of the counsellor
	address		=models.CharField(max_length=200)

	# phone number of the counsellor
	phoneNumber =models.CharField(max_length=20)

	#email address of the counsellor
	email=models.EmailField(default='no_name@gmail.com')

	#education of the counsellor
	education	=models.TextField(blank='true', null='true')

	def get_absolute_url(self):
		return reverse('counsellor:all-counsellor-list')

counsellor/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Counsellor

from .form import CounsellorForm

from django.http import HttpResponse

from availability.models import Shifts, Availability
from availability.forms import AvailabilityForm
from appointments.models import Appointment

from django.views.generic import(
        CreateView,
        DetailView,
        ListView,
        UpdateView,
        DeleteView
    )


# Create your views here.
def counsellor_form_view(request):
    form = CounsellorForm(request.POST or None)
    errors = "";
    if form.is_valid():
        form.save()
        errors = form.errors
        form = CounsellorForm()
        return redirect('counsellor:counsellor-login')

    context = {
        'form': form,
    }
    context['some_string'] = errors

    return render(request, "counsellor/counsellor_form.html", {'form': form,'error':errors})

def counsellor_details_view(request):
    obj = Counsellor.objects.all()
    context = {
        'counsellor_list': obj,
    }
    return render(request, "counsellor/details.html", context)

def counsellor_details_with_availability_view(request):
    obj = Counsellor.objects.all()
    context = {
        'counsellor_list': obj,
    }
    return render(request, "counsellor/counsellor-details.html", context)

def counsellor_login_view(request):
    counsellorName=None
    name="User"
    counsellorID=None
    loadPage=None
    if request.method=='GET':
        if 'action' in request.GET:
            action=request.GET.get('action')
            if action=='logout':
                if request.session.has_key('counsellorName'):
                    request.session.flush()
                return redirect('counsellor:counsellor-login')

        if 'counsellorName' in request.session:
            counsellorName=request.session['counsellorName']
            counsellorID=request.session['counsellorID']
            name        = Counsellor.objects.get(id=counsellorID).name
            print(request.session.get_expiry_age())

    elif request.method=='POST':
        username = request.POST.get("username"," ")
        password = request.POST.get("password"," ")
        obj = Counsellor.objects.filter(username=username,password=password)
        context = {'error':" ", "code" : 202}
        print(obj)
        if 'action' in request.POST:
            action=request.POST.get('action')
            print(action)
        if not obj:
            username=None
            context['error'] = "Username or password is incorrect. Please try again!";
            context['code'] = 422
            return render(request, "counsellor/counsellor-login.html", context)
        else:
            context['code '] = 202
            name=obj[0].name
            counsellorID=obj[0].id
            counsellorName=username
            request.session['counsellorName']=counsellorName
            request.session['counsellorID']=counsellorID

    return render(request, "counsellor/counsellor-login.html", {'username': counsellorName,
                                                                    'name': name, 
                                                                    'action': loadPage, 
                                                                })
#We do not need this view as we are rendering this page from 
#login view using if else condition in our template
"""def counsellor_main_view(request):
    username = request.POST.get("username"," ")
    password = request.POST.get("password"," ")
    obj = Counsellor.objects.filter(username=username,password=password)
    context = {'error':" ", "code" : 202}
    print(obj)
    if not obj:
        context['error'] = "Username or password is incorrect. Please try again!";
        context['code'] = 422
        return render(request, "counsellor/counsellor-login.html", context)
    else:
        context['code '] = 202
        context['name']=obj[0].name
        return render(request, "counsellor/counsellor-main.html", context) """

def all_counsellor_list_view(request):
    obj = Counsellor.objects.all()
    context={
        'all_counsellors':obj,
    }
    return render(request, 'counsellor/all-counsellor-list.html',context)

def edit_counsellor_view(request, id):
    counsellor = Counsellor.objects.get(id=id)
    return render(request, "counsellor/edit-counsellor.html", {'counsellor':counsellor})

def update_counsellor_view(request,id):
    print(id)
    counsellor=Counsellor.objects.get(id=id)
    form= CounsellorForm(request.POST or None, instance=counsellor)
    errors = "";
    if form.is_valid():
        form.save()
    return redirect("counsellor:all-counsellor-list")

def delete_counsellor_view(request,id):
    counsellor = Counsellor.objects.get(id=id)
    counsellor.delete()
    return redirect("counsellor:all-counsellor-list")

def my_availability_view(request):
    if 'counsellorName' in request.session:
        user_id=request.session['counsellorID']
        print(user_id)

        # get availability dates
        availabilityList=Availability.objects.filter(counsellor_id=user_id)

        # get availability shifts
        shifts= Shifts.objects.all()


        if request.method == 'POST':
            date = request.POST.get("availableDate"," ")

            #get the counsellor object
            counsellor=Counsellor.objects.get(id=user_id)

            #create availability object
            availability=Availability(availableDate=date, counsellor=counsellor)

            #save availability
            availability.save()

            # get new availability list
            availabilityList=Availability.objects.filter(counsellor_id=user_id)

        context={
            'availabilityList': availabilityList,
            'shifts'          : shifts,
        }

        return render(request,"counsellor/my-availability.html",context)
    else:
        return redirect('counsellor:counsellor-login')


def give_availability_view(request):
    if 'counsellorName' in request.session:
        context = {'error':" ", "code" : 202}
        return render(request, 'counsellor/give-availability.html', context)

    else:
        return redirect('counsellor:counsellor-login')


def show_availability_view(request, id):
    if request.method=='POST':
        print('POST detected at show availability')
        bookingDate=request.POST.get('bookingDate')
        print("This is bookingDate"+bookingDate)

    availabilityList=Availability.objects.filter(counsellor_id=id)
    counsellorName = Counsellor.objects.get(id=id).name
    shifts=Shifts.objects.all()

    context={
        'availabilityList': availabilityList,
        'shifts'          : shifts,
        'counsellor_id'   : id,
        'counsellorName': counsellorName,
    }
    return render(request, "counsellor/show-availability.html",context)

def my_appointments_view(request):
    if 'counsellorName' in request.session:
        counsellor_id=request.session['counsellorID']
        appointments=Appointment.objects.filter(counsellor_id=counsellor_id)
        context = {
            'appointments': appointments
        }
        return render(request,'counsellor/my-appointments.html', context)

    else:
        return redirect('counsellor:counsellor-login')

def my_clients_view(request):
    if 'counsellorName' in request.session:
        counsellor_id=request.session['counsellorID']
        appointments=Appointment.objects.filter(counsellor_id=counsellor_id)
        clients=[]
        for appoinment in appointments:
            if appoinment.client.name not in clients:
                clients.append(appoinment.client.name)

        context = {
            'clients': clients
        }
        return render(request,'counsellor/my-clients.html', context)

    else:
        return redirect('counsellor:counsellor-login')


class DeleteAppointmentView(DeleteView):
    template_name='counsellor/delete-appointment.html'
    
    queryset=Appointment.objects.all()

    def get_success_url(self):
        return reverse("counsellor:my-appointments")

def my_notifications_view(request):
    if 'counsellorName' in request.session:
        counsellor_id=request.session['counsellorID']
        appointments=Appointment.objects.filter(counsellor_id=counsellor_id)
        context = {
            'appointments': appointments
        }
        return render(request,'counsellor/my-notifications.html', context)

    else:
        return redirect('counsellor:counsellor-login')

def my_profile_view(request):
    if 'counsellorName' in request.session:
        counsellor_id=request.session['counsellorID']
        counsellor=Counsellor.objects.get(id=counsellor_id)
        context = {
            'counsellor': counsellor
        }
        return render(request,'counsellor/my-profile.html', context)

    else:
        return redirect('counsellor:counsellor-login')

counsellor/templates/counsellor/counsellor-login.html
{%extends 'base.html'%}
{%load static%}
{%block style%}
<script src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script src="{% static '/js/jquery-ui.min.js'%}"></script>
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}


{%block content%}

{% if username is None%}
<h2 style="color: blue; text-align: center; ">Counsellor Login Form</h2>
<div class="row align-items-center h-100">
    <div class="col-3 mx-auto">
        <p style="color: red">{{error}}</p>
        <div class="text-center">
            <img id="profile-img" class="rounded-circle profile-img-card" src="{% static '/image/user.png'%}"
                 alt="animated user">
            <p id="profile-name" class="profile-name-card"></p>
            <form role="form" method="post" class="form-signin">{%csrf_token%}
                <input type="text" name="username" id="username" class="form-control form-group" placeholder="Username"
                       required autofocus>
                <input type="password" name="password" id="inputPassword" class="form-control form-group"
                       placeholder="password" required autofocus>
                <button class="btn btn-lg btn-success btn-block btn-signin" type="submit">Sign In</button>
            </form><!-- /form -->
            <a href="{%url 'counsellor:counsellor-form'%}">
                <button class="btn btn-lg btn-primary btn-block btn-signup">Sign Up</button>
            </a>
        </div>
    </div>
</div>

{% else %}

<div id="page-content-wrapper">
    <div class="page-content">
        <div class="container-fluid">
            <b style="font-size:20px;">Welcome, {{name}}</b>
            <div class="row">
                <div class="col-md-3">
                    <div class="background-block">
                        <a href="{% url 'counsellor:my-availability'%}">
                            <h5 class="head-style">MY AVAILABILITY</h5>
                            <div class="text-right image-style">
                                <img src="{% static '/image/apps.png' %}" class="img-spacings" calt="Apps">

                            </div>
                        </a>
                    </div>

                </div>

                <div class="col-md-3">
                    <a href="{%url 'counsellor:my-profile'%}">

                        <div class="background-block">
                            <h5 class="head-style">MY PROFILE</h5>
                            <div class="text-center image-style">
                                <img src="{% static '/image/profile.png' %}" class="img-spacings"
                                     calt="Apps">
                            </div>
                        </div>
                    </a>

                </div>

                <div class="col-md-2">
                    <a href="{%url 'counsellor:my-notifications'%}">

                        <div class="background-block">
                            <h5 class="head-style">NOTIFICATIONS </h5>

                            <div class="text-center image-style">
                                <img src="{% static '/image/notification-bell.png' %}" class="img-spacings"
                                     calt="Apps">

                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-md-2">


                    <div class="background-block">
                        <a href="{%url 'counsellor:my-appointments'%}">
                            <h5 class="head-style">MY APPOINTMENTS</h5>

                            <div class="text-center image-style">
                                <img src="{% static '/image/horizontal-or-vertical-paper-position-interface-button.png' %}"
                                     class="img-spacings" calt="Apps">

                            </div>
                        </a>
                    </div>

                </div>
            </div>

            <div class="row" style="margin-top: 10px;">
                <div class="col-md-6">


                    <div class="background-block">
                        <a href="{%url 'counsellor:my-clients'%}">
                            <h5 class="head-style">MY PATIENTS</h5>

                            <div class="text-right image-style">
                                <img src="{% static '/image/boy-with-tie-reading-a-speech.png' %}"
                                     class="img-spacings"
                                     calt="Apps">

                            </div>
                        </a>
                    </div>


                    <div class="row" style="margin-top: 10px;">
                    </div>
                </div>


                <div class="col-md-4">
                    <a href="{%url 'counsellor:counsellor-login'%}?action=logout" class="head-style">
                        <div class="background-block">
                            <h5 class="head-style">
                                LOGOUT
                            </h5>

                            <div class="text-right image-style">
                                <img src="{% static '/image/red-logout.png' %}"
                                     class="img-spacings" alt="Apps">


                            </div>
                        </div>
                    </a>
                </div>

            </div>

        </div>
    </div>
</div>
{% endif %}
{%endblock%}

counsellor/templates/counsellor/counsellor_form.html
{%extends  'base.html'%}

{%block content%}
<h3 style="color: blue; text-align: center; ">Counsellor Registration Form</h3>
<div class="row col-md-12">	
    <div class="col-md-4 offset-md-4">
        {{error}}
        <form method='POST'> {%csrf_token%}
            <table>
                {{form.as_table}}
            </table>
            <input type='submit' class="btn btn-success" value='Save'/>
        </form>

    </div>

</div>

{% endblock%}

counsellor/templates/counsellor/my-availability.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
{%endblock%}
{%block style%}
<script type="text/javascript" src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script type="text/javascript"  src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!--<script type="text/javascript"  src="{% static '/js/jquery-ui.min.js'%}"></script>-->
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}
{%block content%}
<div id="page-content-wrapper-table">
    <div class="page-content">
        <div class="container-fluid">
             <div class="row pull-right">
                <a href="{%url 'counsellor:counsellor-login'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK TO DASHBOARD</button>
                </a>
              </div>
			<div class="row title-head">
                <div class="col-md-12">
                    <div class="title-line">
                        <span class="page-name">My Availability</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1">
                   <a href="{%url 'counsellor:give-availability'%}" class="none-decoration">
                        <button class="btn btn-small btn-primary btn-add" title="Provide Availability">Provide Availability</button>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 table-responsive">
                    <table class="table table-style" id="counsellorTable">
                        <thead>
                        <tr class="row-bg">
                            <th>SN.</th>
                            <th>Date Available </th>
                            <th>Time Available </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for availability in availabilityList%}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{availability.availableDate}}</td>
                            
                            <td>
                            	{% for shift in shifts%}
                            	{{shift.workhoursFrom}}-{{shift.workhoursTo}},
                            	{%endfor%}
                            </td>
                            
                            <td>
                                <ul class="btn-list-inline">
                                    <li>
										<a href="{% url 'availability:update-availability' pk=availability.id%}">
                                            <input type="submit" class="btn btn-small btn-success" value="EDIT"/>
                                        </a>
                                    </li>
                                    <li>
                                         <a href="{% url 'availability:delete-availability' pk=availability.id%}">
                                            <button type="button" class="btn btn-small btn-danger delete">
                                                DELETE
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

counsellor/templates/counsellor/show-availability.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
{%endblock%}
{%block style%}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}?0000000000">
{%endblock%}
{%block content%}
<div id="page-content-wrapper-form">
    <div class="page-content">

        <div class="container-fluid">
            <div class="row">
                <a href="{%url 'client:client-login'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK TO DASHBOARD</button>
                </a>
            </div>
            <div class="row title-head">
                <div class="col-md-3">
                    <div class="title-line">
                        <span style="font-weight:bold;font-size:18px;">Click on the available dates for {{counsellorName}} </span>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <table class="table table-style" id="availabilityTable">

                    <tbody>
                    {%if availabilityList%}
                    {% for availability in availabilityList %}
                    <tr>
                        <td>
                            <a class="list-group-item" id="list-{{forloop.counter}}-list"
                               data-toggle="list"
                               href="#list-{{forloop.counter}}" role="" aria-controls="{{forloop.counter}}">{{availability.availableDate}}</a>
                        </td>
                    </tr>
                    {%endfor%}
                    {%endif%}
                    </tbody>
                </table>


            </div>
            <div class="col-md-7">

                <div class="tab-content" id="nav-tabContent">

                    {% for availability in availabilityList%}
                    <div class="tab-pane fade show " id="list-{{forloop.counter}}" role="tabpanel"
                         aria-labelledby="list-{{forloop.counter}}-list">

                        <table class="table table-style" id="counsellorTable">
                            <thead>
                            <tr class="row-bg">
                                <th>SN.</th>
                                <th>Availability</th>
                            </tr>
                            </thead>
                            <tbody>
                            {%for shift in shifts%}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>
                                    <a href="{% url 'client:create-appointment'%}?counsellorID={{counsellor_id}}&workhoursFrom={{shift.workhoursFrom}}&workhoursTo={{shift.workhoursTo}}&bookingDate={{availability.availableDate}}">{{shift.workhoursFrom}}
                                        To {{shift.workhoursTo}}</a></td>

                            </tr>
                            {%endfor%}
                            </tbody>
                        </table>
                    </div>
                    {%endfor%}
                </div>

            </div>

        </div>

        <div class="col-md-4">
            <a href="{%url 'counsellor:counsellor-details-with-availability'%}">
                <button class="btn btn-primary btn-lg" title="" type="button">Back</button>
            </a>
        </div>

    </div>
</div>
{% endblock%}