OnlineBookingSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, about_view, contact_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('counsellor/', include('counsellor.urls')),
    path('client/', include('client.urls')),
    path('admin/', include('systemAdmin.urls')),
    path('availability/', include('availability.urls')),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

client/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	client_login_view,
    client_form_view,
    all_client_list_view,
    edit_client_view,
    update_client_view,
    delete_client_view,
    create_appointment_view,
    my_appointments_view,
    my_notifications_view,
    my_counsellors_view,
    DeleteAppointmentView,
    my_profile_view,
    reschedule_appointment_view,
)

app_name="client"

urlpatterns=[
	path('login/', client_login_view, name='client-login'),
    path('form/', client_form_view, name='client-form'),
    path('list/',all_client_list_view, name='all-client-list'),
    path('edit/<int:id>',edit_client_view, name='edit-client'),
    path('update/<int:id>',update_client_view, name='update-client'),
    path('delete/<int:id>',delete_client_view, name='delete-client'),
    path('create-appointment/', create_appointment_view, name='create-appointment'),
    path('my-appointment/', my_appointments_view, name='my-appointment'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('my-profile/', my_profile_view, name='my-profile'),
    path('my-counsellors/', my_counsellors_view, name='my-counsellors'),
    path('<int:pk>/reschedule-appointment/', reschedule_appointment_view, name='reschedule-appointment'),
    path('<int:pk>/delete-appointment/', DeleteAppointmentView.as_view(), name='delete-appointment'),
]

counsellor/urls.py
from django.urls import path

from .views import(
	counsellor_details_view,
	counsellor_details_with_availability_view,
	counsellor_form_view,
	counsellor_login_view,
    all_counsellor_list_view,
    edit_counsellor_view,
    update_counsellor_view,
    delete_counsellor_view,
    my_availability_view,
    give_availability_view,
    show_availability_view,
    my_clients_view,
    my_appointments_view,
    my_notifications_view,
    my_profile_view,
    DeleteAppointmentView,
)

app_name="counsellor"

urlpatterns=[
	path('', counsellor_details_view, name='counsellor-details'),
	path('counsellor-details/', counsellor_details_with_availability_view, name='counsellor-details-with-availability'),
    path('form/', counsellor_form_view, name='counsellor-form'),
    path('login/', counsellor_login_view, name='counsellor-login'),
    path('list/',all_counsellor_list_view, name='all-counsellor-list'),
    path('edit/<int:id>',edit_counsellor_view, name='edit-counsellor'),
    path('update/<int:id>',update_counsellor_view, name='update-counsellor'),
    path('delete/<int:id>',delete_counsellor_view, name='delete-counsellor'),
    path('give-availability/',give_availability_view, name='give-availability'),
    path('my-availabiltiy/',my_availability_view, name='my-availability'),
    path('show-availability/<int:id>',show_availability_view, name='show-availabiltiy'),
    path('my-clients/',my_clients_view, name='my-clients'),
    path('my-appointments/',my_appointments_view, name='my-appointments'),
    path('my-notifications/',my_notifications_view, name='my-notifications'),
    path('my-profile/',my_profile_view, name='my-profile'),
    path('<int:pk>/delete-appointments/',DeleteAppointmentView.as_view(), name='delete-appointments'),
]

manage/manage/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

systemAdmin/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	admin_login_view,
    admin_change_password_view,
    admin_update_password_view,
    CreateWorkHoursView,
    UpdateWorkHoursView,
    WorkHoursListView,
    WorkHoursUpdateView,
    WorkHoursDeleteView,
    my_notifications_view,
    all_appointments_view,
    DeleteAppointmentsView,
    CreateCounsellorView,
    CreateClientView,
)


app_name='systemAdmin'
urlpatterns=[
	path('logIn/',admin_login_view,name='admin-logIn'),
    path('change-password/', admin_change_password_view, name='admin-change-password'),
    path('update-password/', admin_update_password_view, name='admin-update-password'),
    path('create-workhours/', CreateWorkHoursView.as_view(), name='create-workhours'),
    path('<int:pk>/update-workhours/', UpdateWorkHoursView.as_view(), name='update-workhours'),
    path('list-workhours/', WorkHoursListView.as_view(), name='list-workhours'),
    path('<int:pk>/update-workhours/', WorkHoursUpdateView.as_view(), name='update-workhours'),
    path('<int:pk>/delete-workhours/', WorkHoursDeleteView.as_view(), name='delete-workhours'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('all-appointments/', all_appointments_view, name='all-appointments'),
    path('create-counsellor/', CreateCounsellorView.as_view(), name='create-counsellor'),
    path('create-client/', CreateClientView.as_view(), name='create-client'),
    path('<int:pk>/delete-appointments/', DeleteAppointmentsView.as_view(), name='delete-appointments'),
   
]

client/models.py
from django.db import models
from django import forms
from django.urls import reverse


# Create your models here.
class Client(models.Model):
    # max_length is a required field for char field
    # username of the client
    username = models.CharField(max_length=100)

    # login password of the user
    password = models.CharField(max_length=32, default="mydjango123")

    # username of the client
    name = models.CharField(max_length=100)

    # email address of the client
    email = models.EmailField(default='no_name@gmail.com')

    # phone number of the client
    phoneNumber = models.CharField(max_length=20)

    # description of the client
    description = models.TextField(blank='true', null='true')

    def get_absolute_url(self):
        return reverse("client:all-client-list")

client/views.py
from django.shortcuts import render, redirect

from .models import Client
from counsellor.models import Counsellor
from appointments.models import Appointment
from django.contrib import messages
from django.urls import reverse

from appointments.models import Appointment
from availability.models import Availability, Shifts

from .form import ClientForm
from django.core.mail import send_mail

from django.views.generic import(
        CreateView,
        DetailView,
        ListView,
        UpdateView,
        DeleteView
    )


# Create your views here.
def client_initial_view(request):
    return render(request, "client/index.html")


def client_login_view(request):
    clientName=None
    name="User"
    clientID=None
    loadPage=None
    if request.method=='GET':
        if 'action' in request.GET:
            action=request.GET.get('action')
            if action=='logout':
                if request.session.has_key('clientName'):
                    request.session.flush()
                return redirect('client:client-login')

        if 'clientName' in request.session:
            username=request.session['clientName']
            clientName=username
            clientID= request.session['clientID']
            name=Client.objects.get(id=clientID).name
            print(request.session.get_expiry_age())

    elif request.method=='POST':
        username = request.POST.get("username"," ")
        password = request.POST.get("password"," ")
        obj = Client.objects.filter(username=username,password=password)
        context = {'error':" ", "code" : 202}
        print(obj)
        if 'clientName' in request.POST:
            action=request.POST.get('action')
            print(action)
        if not obj:
            username=None
            context['error'] = "Username or password is incorrect. Please try again!";
            context['code'] = 422
            return render(request, "client/client-login.html", context)
        else:
            context['code '] = 202
            name=obj[0].name
            clientID=obj[0].id
            clientName=username
            request.session['clientName']=clientName
            request.session['clientID']=clientID

    return render(request, "client/client-login.html", {'username': clientName,
                                                                    'name': name, 
                                                                    'action': loadPage, 
                                                                })


def client_form_view(request):
    form = ClientForm(request.POST or None)
    errors = "";
    if form.is_valid():
        form.save()
        errors = form.errors
        form = ClientForm()
        return redirect('client:client-login')

    context = {
        'form': form,
    }
    context['some_string'] = errors

    return render(request, "client/client-form.html", {'form': form, 'error': errors})

def all_client_list_view(request):
    obj = Client.objects.all()
    context={
        'all_clients':obj,
    }
    return render(request, 'client/all-client-list.html',context)

def edit_client_view(request, id):
    client = Client.objects.get(id=id)
    return render(request, "client/edit-client.html", {'client':client})

def update_client_view(request,id):
    print(id)
    client = Client.objects.get(id=id)
    form= ClientForm(request.POST or None, instance=client)
    errors = "";
    if form.is_valid():
        form.save()
    return redirect("client:all-client-list")

def delete_client_view(request,id):
     client = Client.objects.get(id=id)
     client.delete()
     return redirect("client:all-client-list")

def create_appointment_view(request):
    if 'clientName' in request.session:
        if request.method=='GET':
            if 'counsellorID' in request.GET:
                counsellor_id=request.GET.get('counsellorID')
            if 'workhoursFrom' in request.GET:
                workhoursFrom=request.GET.get('workhoursFrom')
            if 'workhoursTo' in request.GET:
                workhoursTo=request.GET.get('workhoursTo')
                bookingTime=workhoursFrom+" To "+workhoursTo
                print(bookingTime)

            if 'bookingDate' in request.GET:
                bookingDate=request.GET.get('bookingDate')
                print(bookingDate)
        client_id=request.session['clientID']
        counsellor=Counsellor.objects.get(id=counsellor_id)
        client=Client.objects.get(id=client_id)
        appointment=Appointment(appointmentDate=bookingDate, appointmentTime=bookingTime, 
            counsellor=counsellor, client=client)
        appointment.save()

        #sending confirmation email
        try: 
            send_mail(
                '7Day Psychology Center',
                'Hi '+client.name+", you have an appointment with "+counsellor.name+" scheduled on "+
                bookingDate+" at "+bookingTime,
                'bdipendra01@gmail.com',
                ['bhandaridipendra94@gmail.com'],
                fail_silently=False,
            )

            messages.info(request, "Your appointment with "+counsellor.name+" has been booked successfully.")
            context = {
                'message': "Appointment booked!"
            }
        except: 
            messages.info(request, "Cannot send email. Verify your email address")
            
        return redirect('client:my-appointment')

    else:
        return redirect('client:client-login')


def my_appointments_view(request):
    if 'clientName' in request.session:
        client_id=request.session['clientID']
        appointments=Appointment.objects.filter(client_id=client_id)
        context = {
            'appointments': appointments
        }
        return render(request,'client/my-appointments.html', context)

    else:
        return redirect('client:client-login')

def my_counsellors_view(request):
    if 'clientName' in request.session:
        client_id=request.session['clientID']
        appointments=Appointment.objects.filter(client_id=client_id)
        counsellors=[]
        for appoinment in appointments:
            if appoinment.counsellor.name not in counsellors:
                counsellors.append(appoinment.counsellor.name)

        context = {
            'counsellors': counsellors
        }
        return render(request,'client/my-counsellors.html', context)

    else:
        return redirect('client:client-login')


class DeleteAppointmentView(DeleteView):
    template_name='client/delete-appointment.html'
    
    queryset=Appointment.objects.all()

    def get_success_url(self):
        return reverse("client:my-appointment")

def my_notifications_view(request):
    if 'clientName' in request.session:
        client_id=request.session['clientID']
        appointments=Appointment.objects.filter(client_id=client_id)
        context = {
            'appointments': appointments
        }
        return render(request,'client/my-notifications.html', context)

    else:
        return redirect('client:client-login')

def my_profile_view(request):
    if 'clientName' in request.session:
        client_id=request.session['clientID']
        client=Client.objects.get(id=client_id)
        context = {
            'client': client
        }
        return render(request,'client/my-profile.html', context)

    else:
        return redirect('client:client-login')

def  reschedule_appointment_view(request, pk):
    if 'clientName' in request.session:
        client_id=request.session['clientID']
        appointment_id=pk
        appointment=Appointment.objects.get(id=appointment_id)
        counsellor_id=appointment.counsellor.id
        availability=Availability.objects.filter(counsellor_id=counsellor_id)
        shifts=Shifts.objects.all()
        context = {
            'appointment': appointment,
            'availability': availability,
            'shifts': shifts,
        }

        if request.method=='POST':
            bookingDate=request.POST.get('booking_date')
            bookingTime=request.POST.get('booking_time')
            print(bookingDate+"and"+bookingTime)
            appointment.appointmentDate=bookingDate
            appointment.appointmentTime=bookingTime
            appointment.save()
            return redirect('client:my-appointment')



        return render(request,'client/reschedule-appointment.html', context)

    else:
        return redirect('client:client-login')

client/templates/client/all-client-list.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
{%endblock%}
{%block style%}
<script type="text/javascript" src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script type="text/javascript"  src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!--<script type="text/javascript"  src="{% static '/js/jquery-ui.min.js'%}"></script>-->
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}
{%block content%}
<div id="page-content-wrapper-table">
    <div class="page-content">
        <div class="container-fluid">
            <div class="row pull-right">
                <a href="{%url 'systemAdmin:admin-logIn'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK TO DASHBOARD</button>
                </a>
              </div>
            <div class="row title-head">
                <div class="col-md-12">
                    <div class="title-line">
                        <span class="page-name">Client List</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1">
                    <a href="{%url 'systemAdmin:create-client'%}" class="none-decoration">
                        <button class="btn btn-small btn-primary btn-add" title="Add new">ADD CLIENT</button>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 table-responsive">
                    <table class="table table-style" id="clientTable">
                        <thead>
                        <tr class="row-bg">
                            <th>SN.</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Description</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {%if all_clients%}
                        {%for client in all_clients%}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{client.name}}</td>
                            <td>{{client.phoneNumber}}</td>
                            <td>{{client.email}}</td>
                            <td>{{client.description}}</td>
                            <td>
                                <ul class="btn-list-inline">
                                    <li>
                                        <a href="/client/edit/{{client.id}}">
                                            <input type="submit" class="btn btn-small btn-success" value="EDIT"/>
                                        </a>
                                    </li>
                                    <li>
                                         <a href="/client/delete/{{client.id}}">
                                            <button type="button" class="btn btn-small btn-danger delete">
                                                DELETE
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {%endfor%}
                        {%endif%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}
{%block footer%}
<script>
    $(".delete").click(function(){
            var ans = confirm('Are you sure to delete?')
            if(ans)
                return true
            else
                return false
     });

</script>
{%endblock%}

client/templates/client/client-form.html
{%extends  'base.html'%}

{%block content%}
<h2 style="color: blue; text-align: center; ">New Client Form</h2>
<div class="row col-md-12">
    <div class="col-md-4 offset-md-4">
        {{error}}
        <form method='POST'> {%csrf_token%}
            <table>
                {{form.as_table}}
            </table>
            <input type='submit' class="btn btn-success btn-lg" value='Save'/>
        </form>

    </div>

</div>

{% endblock%}

client/templates/client/client-login.html
{%extends 'base.html'%}
{%load static%}
{%block style%}
<script src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script src="{% static '/js/jquery-ui.min.js'%}"></script>
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}


{%block content%}

{% if username is None%}
<h2 style="color: blue; text-align: center; ">Client Login Form</h2>
<div class="row align-items-center h-100">
    <div class="col-3 mx-auto">
        <p style="color: red">{{error}}</p>
        <div class="text-center">
            <img id="profile-img" class="rounded-circle profile-img-card" src="{% static '/image/avatar.png'%}"
                 alt="animated user">
            <p id="profile-name" class="profile-name-card"></p>
            <form role="form" method="post" class="form-signin">{%csrf_token%}
                <input type="text" name="username" id="username" class="form-control form-group" placeholder="Username"
                       required autofocus>
                <input type="password" name="password" id="inputPassword" class="form-control form-group"
                       placeholder="password" required autofocus>
                <button class="btn btn-lg btn-success btn-block btn-signin" type="submit">Sign In</button>
            </form><!-- /form -->
            <a href="{%url 'client:client-form'%}">
                <button class="btn btn-lg btn-primary btn-block btn-signup">Sign Up</button>
            </a>
        </div>
    </div>
</div>

{% else %}


<div id="page-content-wrapper">
    <div class="page-content">
        <div class="container-fluid">
            <b style="font-size:20px;">Welcome, {{name}}</b>
            <div class="row">
                <div class="col-md-3">
                    <div class="background-block">
                        <a href="{%url 'client:my-appointment'%}">
                            <h5 class="head-style">MY APPOINTMENTS</h5>

                            <div class="text-right image-style">
                                <img src="{% static '/image/horizontal-or-vertical-paper-position-interface-button.png' %}"
                                     class="img-spacings" calt="Apps">
                            </div>
                        </a>
                    </div>

                </div>

                <div class="col-md-3">

                    <div class="background-block">
                        <a href="{%url 'client:my-profile'%}">
                            <h5 class="head-style">MY PROFILE</h5>
                            <div class="text-center image-style">
                                <img src="{% static '/image/profile.png' %}" class="img-spacings"
                                     calt="Apps">
                            </div>
                        </a>
                    </div>

                </div>

                <div class="col-md-2">


                    <div class="background-block">
                        <a href="{%url 'client:my-notifications'%}">
                            <h5 class="head-style">NOTIFICATIONS </h5>

                            <div class="text-center image-style">
                                <img src="{% static '/image/notification-bell.png' %}" class="img-spacings"
                                     calt="Apps">

                            </div>
                        </a>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="background-block">
                        <a href="{%url 'client:my-counsellors'%}">
                            <h5 class="head-style">MY COUNSELLORS</h5>

                            <div class="text-center image-style">

                                <img src="{% static '/image/boy-with-tie-reading-a-speech.png' %}"
                                     class="img-spacings"
                                     calt="Apps">

                            </div>
                        </a>
                    </div>

                </div>
            </div>

            <div class="row" style="margin-top: 10px;">
                <div class="col-md-6">
                    <a href="{%url 'counsellor:counsellor-details-with-availability'%}">
                        <div class="background-block">
                            <h5 class="head-style">MAKE A BOOKING</h5>
                            <div class="text-right image-style">
                                <img src="{% static '/image/apps.png' %}" class="img-spacings" calt="Apps">
                            </div>
                        </div>
                    </a>
                    <div class="row" style="margin-top: 10px;">
                    </div>
                </div>
                <div class="col-md-4">
                    <a href="{%url 'client:client-login'%}?action=logout" class="head-style">
                        <div class="background-block">
                            <h5 class="head-style">
                                LOGOUT
                            </h5>

                            <div class="text-right image-style">
                                <img src="{% static '/image/red-logout.png' %}"
                                     class="img-spacings" alt="Apps">


                            </div>
                        </div>
                    </a>
                </div>

            </div>

        </div>
    </div>
</div>
{% endif %}
{%endblock%}

client/templates/client/my-appointments.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
{%endblock%}
{%block style%}
<script type="text/javascript" src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script type="text/javascript"  src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!--<script type="text/javascript"  src="{% static '/js/jquery-ui.min.js'%}"></script>-->
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}
{%block content%}
<div id="page-content-wrapper-table">
    <div class="page-content">
        {%if messages%}
        {%for message in messages%}
        <h4 style="color: green">{{message}}</h4>
        {%endfor%}
        {%endif%}
        <div class="container-fluid">
            <div class="row pull-right">
                <a href="{%url 'client:client-login'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK TO DASHBOARD</button>
                </a>
              </div>
			<div class="row title-head">
                <div class="col-md-12">
                    <div class="title-line">
                        <span class="page-name">My Appointments</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                    <a href="{%url 'counsellor:counsellor-details-with-availability'%}" class="none-decoration">
                            <button class="btn btn-small btn-primary btn-add" title="book">  MAKE A NEW BOOKING</button>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 table-responsive">
                    <table class="table table-style" id="counsellorTable">
                        <thead>
                        <tr class="row-bg">
                            <th>SN.</th>
                            <th>Counsellor Name </th>
                            <th>Booking Date </th>
                            <th>Booking Time </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for appointment in appointments%}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{appointment.counsellor.name}}</td>
                            <td>{{appointment.appointmentDate}}</td>
                            <td>{{appointment.appointmentTime}}</td>
                            
                            <td>
                                <ul class="btn-list-inline">
                                    <li>
                                        <a href="{%url 'client:reschedule-appointment' pk=appointment.id%}">
                                            <input type="submit" class="btn btn-small btn-success" value="Reschedule appointment"/>
                                        </a>
                                    </li>
                                    
                                    <li>
                                         <a href="{%url 'client:delete-appointment' pk=appointment.id%}">
                                            <button type="button" class="btn btn-small btn-danger delete">
                                                cancel appointment
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}