OnlineBookingSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, about_view, contact_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('counsellor/', include('counsellor.urls')),
    path('client/', include('client.urls')),
    path('admin/', include('systemAdmin.urls')),
    path('availability/', include('availability.urls')),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

client/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	client_login_view,
    client_form_view,
    all_client_list_view,
    edit_client_view,
    update_client_view,
    delete_client_view,
    create_appointment_view,
    my_appointments_view,
    my_notifications_view,
    my_counsellors_view,
    DeleteAppointmentView,
    my_profile_view,
    reschedule_appointment_view,
)

app_name="client"

urlpatterns=[
	path('login/', client_login_view, name='client-login'),
    path('form/', client_form_view, name='client-form'),
    path('list/',all_client_list_view, name='all-client-list'),
    path('edit/<int:id>',edit_client_view, name='edit-client'),
    path('update/<int:id>',update_client_view, name='update-client'),
    path('delete/<int:id>',delete_client_view, name='delete-client'),
    path('create-appointment/', create_appointment_view, name='create-appointment'),
    path('my-appointment/', my_appointments_view, name='my-appointment'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('my-profile/', my_profile_view, name='my-profile'),
    path('my-counsellors/', my_counsellors_view, name='my-counsellors'),
    path('<int:pk>/reschedule-appointment/', reschedule_appointment_view, name='reschedule-appointment'),
    path('<int:pk>/delete-appointment/', DeleteAppointmentView.as_view(), name='delete-appointment'),
]

counsellor/urls.py
from django.urls import path

from .views import(
	counsellor_details_view,
	counsellor_details_with_availability_view,
	counsellor_form_view,
	counsellor_login_view,
    all_counsellor_list_view,
    edit_counsellor_view,
    update_counsellor_view,
    delete_counsellor_view,
    my_availability_view,
    give_availability_view,
    show_availability_view,
    my_clients_view,
    my_appointments_view,
    my_notifications_view,
    my_profile_view,
    DeleteAppointmentView,
)

app_name="counsellor"

urlpatterns=[
	path('', counsellor_details_view, name='counsellor-details'),
	path('counsellor-details/', counsellor_details_with_availability_view, name='counsellor-details-with-availability'),
    path('form/', counsellor_form_view, name='counsellor-form'),
    path('login/', counsellor_login_view, name='counsellor-login'),
    path('list/',all_counsellor_list_view, name='all-counsellor-list'),
    path('edit/<int:id>',edit_counsellor_view, name='edit-counsellor'),
    path('update/<int:id>',update_counsellor_view, name='update-counsellor'),
    path('delete/<int:id>',delete_counsellor_view, name='delete-counsellor'),
    path('give-availability/',give_availability_view, name='give-availability'),
    path('my-availabiltiy/',my_availability_view, name='my-availability'),
    path('show-availability/<int:id>',show_availability_view, name='show-availabiltiy'),
    path('my-clients/',my_clients_view, name='my-clients'),
    path('my-appointments/',my_appointments_view, name='my-appointments'),
    path('my-notifications/',my_notifications_view, name='my-notifications'),
    path('my-profile/',my_profile_view, name='my-profile'),
    path('<int:pk>/delete-appointments/',DeleteAppointmentView.as_view(), name='delete-appointments'),
]

manage/manage/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

systemAdmin/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	admin_login_view,
    admin_change_password_view,
    admin_update_password_view,
    CreateWorkHoursView,
    UpdateWorkHoursView,
    WorkHoursListView,
    WorkHoursUpdateView,
    WorkHoursDeleteView,
    my_notifications_view,
    all_appointments_view,
    DeleteAppointmentsView,
    CreateCounsellorView,
    CreateClientView,
)


app_name='systemAdmin'
urlpatterns=[
	path('logIn/',admin_login_view,name='admin-logIn'),
    path('change-password/', admin_change_password_view, name='admin-change-password'),
    path('update-password/', admin_update_password_view, name='admin-update-password'),
    path('create-workhours/', CreateWorkHoursView.as_view(), name='create-workhours'),
    path('<int:pk>/update-workhours/', UpdateWorkHoursView.as_view(), name='update-workhours'),
    path('list-workhours/', WorkHoursListView.as_view(), name='list-workhours'),
    path('<int:pk>/update-workhours/', WorkHoursUpdateView.as_view(), name='update-workhours'),
    path('<int:pk>/delete-workhours/', WorkHoursDeleteView.as_view(), name='delete-workhours'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('all-appointments/', all_appointments_view, name='all-appointments'),
    path('create-counsellor/', CreateCounsellorView.as_view(), name='create-counsellor'),
    path('create-client/', CreateClientView.as_view(), name='create-client'),
    path('<int:pk>/delete-appointments/', DeleteAppointmentsView.as_view(), name='delete-appointments'),
   
]

templates/about.html
{% extends 'base.html'%}
{%load static%}
{%block content%}
<div class="row">
	<div class="col-md-8 d-flex justify-content-center">
	    <img class="img-responsive center-block" src="{% static '/image/clinic.jpg'%}" style="height:80%; width:80%;"
	                 alt="7 day psychology centre">
	</div>
	<div class="col-4" style="padding: 2vw">
		<p>Established in 2010 and located in the inner west, the 7 Day Psychology Centre is a network of
	            experienced
	            clinical psychologists providing total help for the individual, the partner and the parent.<br>
	        Our clinical psychologists have expertise in adult, adolescent and child disorders. They are all trained in
	        treating depression and anxiety disorders and specialise in a variety of other areas.

	        All our clinical psychologists are registered with the Psychology Board of Australia and endorsed for
	        clinical psychology as an approved area of practice.
	        </p>
	</div>
</div>

{%endblock%}

templates/base.html
<DOCTYPE! html>
  <html>
    <head>
      {% load static%}
      <title>7-day Psychology online booking system</title>
      <link
        rel="stylesheet"
        type="text/css"
        href="{% static '/css/bootstrap.min.css'%}"
      />
      {%block style%} {%endblock%}
      <link
        rel="stylesheet"
        type="text/css"
        href="{% static '/css/style.css'%}?0"
      />
      <script
        type="text/javascript"
        src="{% static '/js/jquery-3.5.0.min.js'%}"
      ></script>
      <script
        type="text/javascript"
        src="{% static '/js/bootstrap.min.js'%}"
      ></script>
    </head>
    <body>
      <div class="wrapper">
        <div class="row">
          <div class="col-sm-2" style="padding-left: 5vw">
            <a href="{%url 'home'%}"
              ><img
                height="150vw"
                src="{% static '/image/logo.png'%}"
                alt="logo"
            /></a>
          </div>
          <div class="col-sm-6" style="padding-top: 30px">
            <h2 class="title">7 Day Psychology</h2>
            <h6>Mental Health is our Priority</h6>
          </div>
          <div class="col-sm-4">{%block header%} {%endblock%}</div>
        </div>

        <div class="row">{% include 'navbar.html'%}</div>
        <div class="row">
          <div class="col-md-12">
            {%block content%} replace the contents {%endblock%}
          </div>
        </div>
      </div>
      <footer class="footer">
        <div class="row">
          <div class="col-md-12">
            <div class="row col-md-12">
              <div class="col-md-6">
                <h5>Phone Number: 044985756</h5>
              </div>
              <div class="col-md-6">
                <h5 class="float-right">Email: 7day-psychology@hotmail.com</h5>
              </div>
            </div>
          </div>

          <div class="col-md-12">
            <div class="col-md-12 text-center">
              &copy 2019 7 Day Psychology centre/ All rights are reserved
            </div>
          </div>
        </div>
      </footer>
    </body>
    {%block footer%} {%endblock%}
  </html>
</DOCTYPE!>

templates/contact.html
{%extends 'base.html'%}
{%block content%}
<div class="row" style="padding: 10vw;">
	<div class="col-3">
		<h3>Contact Counsellors</h3>
		<p>You can directly contact counsellors to the contact numbers provided on the
		counsellors page and book your appoinment.</p>
	</div>
	<div class="col-3">
		<h3>Email Us</h3>
		<p>You can send any queries or issues to 7day-psychology@hotmail.com</p>
	</div>
	<div class="col-4">
		<h3>General Correspondance</h3>
		<p>Any general correspondance should be addressed to The Management 7 
		Day Psychology Centre Suit 12 10 Park Road Auburn, NSW 2144</p>
	</div>
</div>

{%endblock%}

templates/index.html
{% extends 'base.html'%}

{%block header%}
<div class="col-md-12 button-block">

    <h6>Book an appointment
        <a href="{%url 'client:client-login'%}">
            <button type="button" class="btn btn-primary">My Account</button>
        </a>
    </h6>
    <h6>Login as a counsellor
        <a href="{%url 'counsellor:counsellor-login'%}">
        <button type="button" class="btn btn-primary">Login/Signup</button>
    </a></h6>

    <h6>
        <a href="{%url 'systemAdmin:admin-logIn'%}">
        <button type="button" class="btn btn-primary">Login</button>
    </a> as an admin</h6>
</div>
{%endblock%}

{%block content%}
<div class="col-md-12">
    <div class="col-md-12 index-block">
        <h3> 7-Day Psychology</h3>
    </div>
</div>
<div class="col-md-12">
    <div class="col-md-12">
        <p>Established in 2010 and located in the inner west, the 7 Day Psychology Centre is a network of
            experienced
            clinical psychologists providing total help for the individual, the partner and the parent.
        <hr style="display: none">
        Our clinical psychologists have expertise in adult, adolescent and child disorders. They are all trained in
        treating depression and anxiety disorders and specialise in a variety of other areas.

        All our clinical psychologists are registered with the Psychology Board of Australia and endorsed for
        clinical psychology as an approved area of practice.
        </p>
    </div>
</div>
<div class="col-md-12">
    <div class="row col-md-12">
        <div class="col-md-4">
            <table>
                <th>Days</th>
                <th>Opening Hours</th>
                </tr>
                <tr>
                    <td>Monday to Friday</td>
                    <td>10 am to 5 pm</td>
                </tr>
                <tr>
                    <td>Weekends</td>
                    <td> Closed</td>
                </tr>
            </table>
        </div>
        <div class="col-md-8 d-flex justify-content-center">
            <img class="img-responsive center-block" src="./static/image/centre.jpg" style="height:80%; width:80%;"
                 alt="logo">
        </div>
    </div>
</div>

{%endblock%}

templates/navbar.html
<div class="col-md-12">
    <nav class="navbar navbar-expand-sm bg-light nav-pills"  >
        <ul class="navbar-nav" style="font-size: 20px">
            <li class="nav-item" style="padding-left:20px;"><a class="nav-link" href="{% url 'home'%}">HOME</a></li>
            <li class="nav-item" style="padding-left:20px;"><a class="nav-link" href="{%url 'counsellor:counsellor-details'%}">COUNSELLORS</a></li>
            <li class="nav-item" style="padding-left:20px;"><a class="nav-link" href="{%url 'about'%}"> ABOUT US</a></li>
            <li class="nav-item" style="padding-left:20px;"><a class="nav-link" href="{%url 'contact'%}"> CONTACT US</a></li>
        </ul>
    </nav>
</div>