OnlineBookingSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pages.views import home_view, about_view, contact_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('counsellor/', include('counsellor.urls')),
    path('client/', include('client.urls')),
    path('admin/', include('systemAdmin.urls')),
    path('availability/', include('availability.urls')),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

client/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	client_login_view,
    client_form_view,
    all_client_list_view,
    edit_client_view,
    update_client_view,
    delete_client_view,
    create_appointment_view,
    my_appointments_view,
    my_notifications_view,
    my_counsellors_view,
    DeleteAppointmentView,
    my_profile_view,
    reschedule_appointment_view,
)

app_name="client"

urlpatterns=[
	path('login/', client_login_view, name='client-login'),
    path('form/', client_form_view, name='client-form'),
    path('list/',all_client_list_view, name='all-client-list'),
    path('edit/<int:id>',edit_client_view, name='edit-client'),
    path('update/<int:id>',update_client_view, name='update-client'),
    path('delete/<int:id>',delete_client_view, name='delete-client'),
    path('create-appointment/', create_appointment_view, name='create-appointment'),
    path('my-appointment/', my_appointments_view, name='my-appointment'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('my-profile/', my_profile_view, name='my-profile'),
    path('my-counsellors/', my_counsellors_view, name='my-counsellors'),
    path('<int:pk>/reschedule-appointment/', reschedule_appointment_view, name='reschedule-appointment'),
    path('<int:pk>/delete-appointment/', DeleteAppointmentView.as_view(), name='delete-appointment'),
]

counsellor/urls.py
from django.urls import path

from .views import(
	counsellor_details_view,
	counsellor_details_with_availability_view,
	counsellor_form_view,
	counsellor_login_view,
    all_counsellor_list_view,
    edit_counsellor_view,
    update_counsellor_view,
    delete_counsellor_view,
    my_availability_view,
    give_availability_view,
    show_availability_view,
    my_clients_view,
    my_appointments_view,
    my_notifications_view,
    my_profile_view,
    DeleteAppointmentView,
)

app_name="counsellor"

urlpatterns=[
	path('', counsellor_details_view, name='counsellor-details'),
	path('counsellor-details/', counsellor_details_with_availability_view, name='counsellor-details-with-availability'),
    path('form/', counsellor_form_view, name='counsellor-form'),
    path('login/', counsellor_login_view, name='counsellor-login'),
    path('list/',all_counsellor_list_view, name='all-counsellor-list'),
    path('edit/<int:id>',edit_counsellor_view, name='edit-counsellor'),
    path('update/<int:id>',update_counsellor_view, name='update-counsellor'),
    path('delete/<int:id>',delete_counsellor_view, name='delete-counsellor'),
    path('give-availability/',give_availability_view, name='give-availability'),
    path('my-availabiltiy/',my_availability_view, name='my-availability'),
    path('show-availability/<int:id>',show_availability_view, name='show-availabiltiy'),
    path('my-clients/',my_clients_view, name='my-clients'),
    path('my-appointments/',my_appointments_view, name='my-appointments'),
    path('my-notifications/',my_notifications_view, name='my-notifications'),
    path('my-profile/',my_profile_view, name='my-profile'),
    path('<int:pk>/delete-appointments/',DeleteAppointmentView.as_view(), name='delete-appointments'),
]

manage/manage/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

systemAdmin/urls.py
from django.urls import path

#putting everything related to a app to the same place is the best practice in django
#it makes the code cleaner, manageable, and makes it able to be released as a third party 
#resource if and when possible
from .views import(
	admin_login_view,
    admin_change_password_view,
    admin_update_password_view,
    CreateWorkHoursView,
    UpdateWorkHoursView,
    WorkHoursListView,
    WorkHoursUpdateView,
    WorkHoursDeleteView,
    my_notifications_view,
    all_appointments_view,
    DeleteAppointmentsView,
    CreateCounsellorView,
    CreateClientView,
)


app_name='systemAdmin'
urlpatterns=[
	path('logIn/',admin_login_view,name='admin-logIn'),
    path('change-password/', admin_change_password_view, name='admin-change-password'),
    path('update-password/', admin_update_password_view, name='admin-update-password'),
    path('create-workhours/', CreateWorkHoursView.as_view(), name='create-workhours'),
    path('<int:pk>/update-workhours/', UpdateWorkHoursView.as_view(), name='update-workhours'),
    path('list-workhours/', WorkHoursListView.as_view(), name='list-workhours'),
    path('<int:pk>/update-workhours/', WorkHoursUpdateView.as_view(), name='update-workhours'),
    path('<int:pk>/delete-workhours/', WorkHoursDeleteView.as_view(), name='delete-workhours'),
    path('my-notifications/', my_notifications_view, name='my-notifications'),
    path('all-appointments/', all_appointments_view, name='all-appointments'),
    path('create-counsellor/', CreateCounsellorView.as_view(), name='create-counsellor'),
    path('create-client/', CreateClientView.as_view(), name='create-client'),
    path('<int:pk>/delete-appointments/', DeleteAppointmentsView.as_view(), name='delete-appointments'),
   
]

systemAdmin/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    username=models.CharField(max_length=100, default="admin")
    password=models.CharField(max_length=100, default="admin")

systemAdmin/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Admin
from counsellor.form import CounsellorForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.generic import(
        CreateView,
        DetailView,
        ListView,
        UpdateView,
        DeleteView
    )
from availability.forms import WorkingHoursForm
from availability.models import Shifts
from counsellor.models import Counsellor
from appointments.models import Appointment
from client.models import Client
from client.form import ClientForm

# Create your views here.
def admin_login_view(request):
    adminName=None
    name="User"
    adminID=None
    loadPage=None
    if request.method=='GET':
        if 'action' in request.GET:
            action=request.GET.get('action')
            if action=='logout':
                if request.session.has_key('adminName'):
                    request.session.flush()
                return redirect('systemAdmin:admin-logIn')

        if 'adminName' in request.session:
            adminName=request.session['adminName']
            adminID=request.session['adminID']
            print(request.session.get_expiry_age())

    elif request.method=='POST':
        username = request.POST.get("username"," ")
        password = request.POST.get("password"," ")
        obj = Admin.objects.filter(username=username,password=password)
        context = {'error':" ", "code" : 202}
        print(obj)
        if 'action' in request.POST:
            action=request.POST.get('action')
            print(action)
        if not obj:
            adminName=None
            context['error'] = "Username or password is incorrect. Please try again!";
            context['code'] = 422
            return render(request, "systemAdmin/admin-login.html", context)
        else:
            context['code '] = 202
            adminID=obj[0].id
            adminName=username
            request.session['adminName']=adminName
            request.session['adminID']=adminID

    return render(request, "systemAdmin/admin-login.html", {'username': adminName,
                                                                    'name': name, 
                                                                    'action': loadPage, 
                                                                })


def admin_change_password_view(request):
   return render(request,"systemAdmin/admin-change-password.html")

def admin_update_password_view(request):
    admin = Admin.objects.get(id=request.user.id)
    password = request.POST.get("password"," ")
    admin.password = password
    admin.save()
    return render(request,"systemAdmin/admin-change-password.html")

class CreateWorkHoursView(CreateView):
    template_name='systemAdmin/create-workhours.html'
    form_class=WorkingHoursForm
    queryset=Shifts.objects.all()

class UpdateWorkHoursView(UpdateView):
    template_name='systemAdmin/create-workhours.html'
    form_class=WorkingHoursForm
    queryset=Shifts.objects.all()

    #def get_object(self):
    #id_=self.kwargs.get("id")
    #return get_object_or_404(Article, id=id_)

    #you can also override the success url by two methos
    #success_url="/" or
    #def get_success_url(self)
    #return "/"

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class WorkHoursListView(ListView):
    # we can reference diffrent template names as well
    # one way is to do this if the templates were inside article foler
    # template_name='articles/article_list.html'
    template_name='systemAdmin/list-workhours.html'
    queryset=Shifts.objects.all()

class WorkHoursUpdateView(UpdateView):
    template_name='systemAdmin/workhours-create.html'
    form_class=WorkingHoursForm
    queryset=Shifts.objects.all()

    #def get_object(self):
    #id_=self.kwargs.get("id")
    #return get_object_or_404(Article, id=id_)

    #you can also override the success url by two methos
    #success_url="/" or
    #def get_success_url(self)
    #return "/"

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class WorkHoursDeleteView(DeleteView):
    template_name='systemAdmin/workhours-delete.html'
    
    queryset=Shifts.objects.all()

    def get_success_url(self):
        return reverse("systemAdmin:list-workhours")

def my_notifications_view(request):
    if 'adminName' in request.session:
        counsellors=Counsellor.objects.all()
        appointments=Appointment.objects.all()
        clients=Client.objects.all()
        context = {
            'appointments': appointments,
            'counsellors' : counsellors,
            'clients'     : clients,
        }
        return render(request,'systemAdmin/my-notifications.html', context)

    else:
        return redirect('systemAdmin:counsellor-logIn')

def all_appointments_view(request):
    if 'adminName' in request.session:
        appointments=Appointment.objects.all()
        context = {
            'appointments': appointments
        }
        return render(request,'systemAdmin/all-appointments.html', context)

    else:
        return redirect('systemAdmin:admin-logIn')

class DeleteAppointmentsView(DeleteView):
    template_name='systemAdmin/delete-appointment.html'
    
    queryset=Appointment.objects.all()

    def get_success_url(self):
        return reverse("systemAdmin:all-appointments")

class CreateCounsellorView(CreateView):
    template_name='systemAdmin/create-counsellor.html'
    form_class=CounsellorForm
    queryset=Counsellor.objects.all()

class CreateClientView(CreateView):
    template_name='systemAdmin/create-client.html'
    form_class=ClientForm
    queryset=Client.objects.all()

systemAdmin/templates/systemAdmin/admin-change-password.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
{%endblock%}
{%block style%}
<script type="text/javascript" src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script type="text/javascript"  src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!--<script type="text/javascript"  src="{% static '/js/jquery-ui.min.js'%}"></script>-->
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}
{%block content%}
<div id="page-content-wrapper-form">
    <div class="page-content">
        <div class="container-fluid">
            {%if messages%}
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {%endif%}
             <form method="POST" class="post-form">{% csrf_token %}
                <div class="row title-head">
                    <div class="col-md-12">
                        <div class="title-line">
                            <span class="page-name">Change Password</span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="row">

                            <div class="col-md-6">
                                <div>
                                    <label>New Password</label>
                                </div>
                                <div class="input-wrapper">
                                    <input type="password" class="form-control input-text" id="newPassword" name="newPassword"
                                           onchange="check()"   value="" required>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div>
                                    <label>Confirm Password</label>
                                </div>
                                <div class="input-wrapper">
                                    <input type="password" class="form-control input-text" id="password" name="password"
                                           value="" required onkeyup="check()">
                                </div><label id="checkStatus"></label>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <a href="{%url 'systemAdmin:admin-update-password'%}"><button class="btn btn-lg btn-primary" title="Submit" type="submit">SUBMIT</button></a>
                            <a href="{%url 'systemAdmin:admin-logIn'%}">
                                          <button class="btn btn-success btn-lg" title="Cancel" type="button">CANCEL</button>
                            </a>
                        </div>
                        <!-- ends here -->
                    </div>
                </div>
        </div>
    </div>
</div>
{%endblock%}
{%block footer%}
<script>
    $(".update").click(function(){
    $("#checkStatus").text("")
            var newPass = $("#newPassword").val();
            var confirm = $("#password").val();
            if (newPass == confirm) {
                $("#checkStatus").text("Password match!!")
                $("#checkStatus").css("color", "green");
                return true

            } else {
                $("#checkStatus").text("Password didn't match!!");
                $("#checkStatus").css("color", "red")
                $("#newPassword").val("");
                $("#password").val("");
                return false

            }
     });

</script>
{%endblock%}

systemAdmin/templates/systemAdmin/admin-login.html
{%extends 'base.html'%}
{%load static%}
{%block style%}
<script src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script src="{% static '/js/jquery-ui.min.js'%}"></script>
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}?1">
{%endblock%}
{%block content%}
{%if username is None%}
<h2 style="color: blue; text-align: center; ">Admin Login Form</h2>
<div class="row align-items-center h-100">
    <div class="col-3 mx-auto">
        <p style="color: red">{{error}}</p>
        <div class="text-center">
            <img id="profile-img" class="rounded-circle profile-img-card" src="{% static '/image/user.png'%}"
                 alt="animated user">
            <p id="profile-name" class="profile-name-card"></p>
            <form action="{% url 'systemAdmin:admin-logIn'%}" method="post" class="form-signin">{%csrf_token%}
                <input type="text" name="username" id="username" class="form-control form-group" placeholder="Username"
                       required autofocus>
                <input type="password" name="password" id="inputPassword" class="form-control form-group"
                       placeholder="password" required autofocus>
                <button class="btn btn-lg btn-success btn-block btn-signin" type="submit">Sign In</button>
            </form><!-- /form -->

        </div>
    </div>
</div>

{%else%}
<div id="page-content-wrapper">
    <div class="page-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                <a href="{%url 'counsellor:all-counsellor-list'%}">
                    <div class="background-block">
                            <h5 class="head-style">COUNSELLORS</h5>

                        <div class="text-center image-style">
                            <a href="{%url 'counsellor:all-counsellor-list'%}">
                                    <img src="{% static '/image/boy-with-tie-reading-a-speech.png' %}"
                                                                     class="img-spacings"
                                                                     alt="Apps">
                            </a>


                        </div>
                    </div>
                </a>

                </div>
                <div class="col-md-2">
                    <a href="{%url 'systemAdmin:admin-change-password'%}">

                    <div class="background-block">

                        <h5 class="head-style">CHANGE MY PASSWORD</h5>
                        <div class="text-center image-style">
                            <img src="{% static '/image/apps.png' %}" class="img-spacings" alt="Apps">

                        </div>

                    </div>
                    </a>

                </div>

                <div class="col-md-2">
                    <div class="background-block">
                        <a href="{% url 'systemAdmin:list-workhours'%}">
                        <h5 class="head-style">MANAGE SHIFTS</h5>

                        <div class="text-center image-style">
                            <img src="{% static '/image/apps.png' %}" class="img-spacings"
                                 calt="Apps"></a>

                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <a href="{%url 'systemAdmin:all-appointments'%}">

                    <div class="background-block">
                        <h5 class="head-style">VIEW APPOINMENTS</h5>

                        <div class="text-center image-style">
                            <img src="{% static '/image/horizontal-or-vertical-paper-position-interface-button.png' %}"
                                 class="img-spacings" alt="Apps">

                        </div>
                    </div>
                    </a>

                </div>
                <div class="col-md-2">
                    <a href="{%url 'systemAdmin:my-notifications'%}">
                    <div class="background-block">
                        <h5 class="head-style">MY NOTIFICATIONS</h5>
                        <div class="text-center image-style">
                            <img src="{% static '/image/notification-bell.png' %}" class="img-spacings"
                                 calt="Apps">
                        </div>
                    </div>
                    </a>

                </div>


            </div>

            <div class="row" style="margin-top: 10px;">
                <div class="col-md-6">

                    <a href="{%url 'client:all-client-list'%}">
                       <div class="background-block">
                            <h5 class="head-style">CLIENTS</h5>

                            <div class="text-right image-style">
                                <img src="{% static '/image/profile.png' %}" class="img-spacings" alt="Apps">
                            </div>
                         </div>
                    </a>
                    <div class="row" style="margin-top: 10px;">
                    </div>
                </div>


                <div class="col-md-4">
                    <a href="{%url 'systemAdmin:admin-logIn'%}?action=logout">
                    <div class="background-block">
                        <h5 class="head-style">LOGOUT</h5>

                        <div class="text-right image-style">
                            <img src="{% static '/image/red-logout.png' %}"
                                                           class="img-spacings" alt="Apps">

                        </div>
                    </div>
                    </a>

                </div>

            </div>

        </div>
    </div>
</div>
{%endif%}
{%endblock%}

systemAdmin/templates/systemAdmin/all-appointments.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
{%endblock%}
{%block style%}
<script type="text/javascript" src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script type="text/javascript"  src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!--<script type="text/javascript"  src="{% static '/js/jquery-ui.min.js'%}"></script>-->
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}
{%block content%}
<div id="page-content-wrapper-table">
    <div class="page-content">
        <div class="container-fluid">
              <div class="row">
                <a href="{%url 'systemAdmin:admin-logIn'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK TO DASHBOARD</button>
                </a>
              </div>
			<div class="row title-head">
                <div class="col-md-12">
                    <div class="title-line">
                        <span class="page-name">Current Appointments</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 table-responsive">
                    <table class="table table-style" id="counsellorTable">
                        <thead>
                        <tr class="row-bg">
                            <th>SN.</th>
                            <th>Counsellor Name </th>
                            <th>Client Name </th>
                            <th>Booking Date </th>
                            <th>Booking Time </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for appointment in appointments%}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{appointment.counsellor.name}}</td>
                            <td>{{appointment.client.name}}</td>
                            <td>{{appointment.appointmentDate}}</td>
                            <td>{{appointment.appointmentTime}}</td>
                            
                            <td>
                                <ul class="btn-list-inline">
                                    
                                    
                                    <li>
                                         <a href="{%url 'systemAdmin:delete-appointments' pk=appointment.id%}">
                                            <button type="button" class="btn btn-small btn-danger delete">
                                                cancel appointment
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

systemAdmin/templates/systemAdmin/create-client.html
{%extends  'base.html'%}

{%block content%}
<h3 style="color: blue; text-align: center; ">Create a new client</h3>
<div class="row col-md-12"> 
    <div class="col-md-4 offset-md-4">
        {{error}}
        <form method='POST'> {%csrf_token%}
            <table>
                {{form.as_table}}
            </table>
            <input type='submit' class="btn btn-success" value='Save'/>
        </form>

    </div>
    <div class="row">
                <a href="{%url 'client:all-client-list'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK</button>
                </a>
            </div>

</div>

{% endblock%}

systemAdmin/templates/systemAdmin/create-counsellor.html
{%extends  'base.html'%}

{%block content%}
<h3 style="color: blue; text-align: center; ">Create a new counsellor</h3>
<div class="row col-md-12"> 
    <div class="col-md-4 offset-md-4">
        {{error}}
        <form method='POST'> {%csrf_token%}
            <table>
                {{form.as_table}}
            </table>
            <input type='submit' class="btn btn-success" value='Save'/>
        </form>

    </div>
    <div class="row">
                <a href="{%url 'counsellor:all-counsellor-list'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK</button>
                </a>
            </div>

</div>

{% endblock%}

systemAdmin/templates/systemAdmin/list-workhours.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
{%endblock%}
{%block style%}
<script type="text/javascript" src="{% static '/js/jquery.dataTables.min.js'%}"></script>
<script type="text/javascript"  src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<!--<script type="text/javascript"  src="{% static '/js/jquery-ui.min.js'%}"></script>-->
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery.dataTables.min.css'%}">
<link rel="stylesheet" type="text/css" href="{% static '/css/jquery-ui.min.css'%}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static '/css/style-counsellor.css'%}">
{%endblock%}
{%block content%}
<div id="page-content-wrapper-table">
    <div class="page-content">
        <div class="container-fluid">
            <div class="row pull-right">
                <a href="{%url 'systemAdmin:admin-logIn'%}">
                    <button class="btn btn-success btn-lg" title="back" type="button">GO BACK TO DASHBOARD</button>
                </a>
            </div>
            <div class="row title-head">
                <div class="col-md-12">
                    <div class="title-line">
                        <span class="page-name">Current Shifts List</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1">
                    <a href="{%url 'systemAdmin:create-workhours'%}" class="none-decoration">
                        <button class="btn btn-small btn-primary btn-add" title="Add new">ADD SHIFT</button>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 table-responsive">
                    <table class="table table-style" id="counsellorTable">
                        <thead>
                        <tr class="row-bg">
                            <th>SN.</th>
                            <th>Start Time </th>
                            <th>End Time </th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {%if object_list%}
						{% for instance in object_list %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{instance.workhoursFrom}}</td>
                            <td>{{instance.workhoursTo}}</td>
                            <td>
                                <ul class="btn-list-inline">
                                    <li>
										<a href="{% url 'systemAdmin:update-workhours' pk=instance.id%}">
                                            <input type="submit" class="btn btn-small btn-success" value="EDIT"/>
                                        </a>
                                    </li>
                                    <li>
                                         <a href="{% url 'systemAdmin:delete-workhours' pk=instance.id%}">
                                            <button type="button" class="btn btn-small btn-danger delete">
                                                DELETE
                                            </button>
                                        </a>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                        {%endfor%}
                        {%endif%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}